[build]
target = "riscv64gc-unknown-none-elf"
rustflags = ['-Clink-arg=-Tsrc/kernel.ld']

[target.riscv64gc-unknown-none-elf]
runner = """
qemu-system-riscv64 \
-machine virt -bios default -nographic -serial mon:stdio --no-reboot \
-drive id=drive0,file=disk/lorem.txt,format=raw \
-device virtio-blk-device,drive=drive0,bus=virtio-mmio-bus.0 \
-kernel """
